#!/usr/bin/env python
import sys
from optparse import OptionParser

from jinja2 import Environment, FileSystemLoader
from jinja2.exceptions import TemplateNotFound

import os.path

ROOT_DIR = os.path.dirname(os.path.abspath(__file__))
TEMPLATE_DIR = os.path.join(ROOT_DIR, 'website/templates/')
SITE_TEMPLATE = 'site/index.html'

import json

def build(opts, args):
    try:
        data = json.loads(open(args[0]).read())
    except ValueError:
        print "Bad input data"
        sys.exit(1)

    env = Environment(loader=FileSystemLoader(TEMPLATE_DIR))
    try:
        tmpl = env.get_template(SITE_TEMPLATE)
    except TemplateNotFound:
        print "No site template."
        sys.exit(1)

    # Note: We want to let rendering exceptions bubble up.
    sys.stdout.write(tmpl.render(data))
    sys.exit(0)


if __name__ == '__main__':
    parser = OptionParser(usage="usage: %prog [options] <input template> <input data>")
    opts, args = parser.parse_args()
    build(opts, args)
