#!/usr/bin/env python
"""
    A simple module to compile the Jinja2 templates
    that comprise the ng-everything.com site's HTML.
"""
import sys
from optparse import OptionParser

from jinja2 import Environment, FileSystemLoader
from jinja2.exceptions import TemplateNotFound

import os.path

ROOT_DIR = os.path.dirname(os.path.abspath(__file__))
TEMPLATE_DIR = os.path.join(ROOT_DIR, 'website/templates/')
SITE_TEMPLATE = 'site/index.html'

import json

def build(opts, args):
    data = {}
    
    # Read the specified data file as JSON.
    if len(args):
        try:
            data = json.loads(open(args[0]).read())
        except ValueError as e:
            sys.stderr.write("Bad input data: %s\n" % e)
            sys.exit(1)

    # Default to the main site template if no input
    # templates are specified.
    input_paths = [SITE_TEMPLATE]
    if len(args) > 1:
        input_path = args[1:]
    
    # Load up all requested templates.
    env = Environment(loader=FileSystemLoader(TEMPLATE_DIR))
    try:
        templates = [env.get_template(path) for path in input_paths]
    except TemplateNotFound as e:
        sys.stderr.write("Template not found: %s\n" % e)
        sys.exit(1)
    
    # Render all reqeusted templates on stdout; this isn't
    # super useful for more than 1 template...
    for template in templates:
        sys.stdout.write(template.render(data))
    
    sys.exit(0)


if __name__ == '__main__':
    parser = OptionParser(usage="usage: %prog [options] [input data] [input file ...]")
    opts, args = parser.parse_args()
    build(opts, args)
